#pragma config(Sensor, S1,     leftSensor,     sensorEV3_Color)
#pragma config(Sensor, S2,     rightSensor,    sensorEV3_Color)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Main line following
float leftSensorValue;
float rightSensorValue;
void lineFollow() {
	if (leftSensorValue < 20) {
		leftSensorValue = -100;
		rightSensorValue = 100;
	}
	if (rightSensorValue < 20) {
		rightSensorValue = -100;
		leftSensorValue = 100;
	}

	setMotorSpeed(leftMotor, leftSensorValue); //Set leftMotor speed
	setMotorSpeed(rightMotor, rightSensorValue); //Set leftMotor speed

}

task main()
{
	while (true) {
		leftSensorValue = getColorReflected(leftSensor); //Left sensor value
		rightSensorValue = getColorReflected(rightSensor); //Right sensor value

		//Tweaking the values
		leftSensorValue = leftSensorValue/3;
		rightSensorValue = rightSensorValue/3;
		//Green
		if (leftSensorValue < 30) {
			if (getColorName(leftSensor) == colorGreen /*|| getColorName(leftSensor) == colorBlue*/) {
				//Check if it's really green or just a false positive
				playSound(soundBlip);
				//turn
				moveMotorTarget(motorC, 360, 80);
				sleep(250);
			}
			else {
				lineFollow();
			}
		}
		else {
			lineFollow();
		}

		if (rightSensorValue < 25) {
			if (getColorName(rightSensor) == colorGreen /*|| getColorName(leftSensor) == colorBlue*/) {
				//Check if it's really green or just a false positive
				playSound(soundBlip);
				//turn
				moveMotorTarget(motorB, 360, 80);
				sleep(250);
			}
			else {
				lineFollow();
			}
		}
		else {
			lineFollow();
		}
	} //end of while loop
} //end of task main
