#pragma config(Sensor, S1,     leftSensor,     sensorEV3_Color)
#pragma config(Sensor, S2,     rightSensor,    sensorEV3_Color)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float leftSensorValue;
float rightSensorValue;

float leftMotorSpeed;
float rightMotorSpeed;

//Line following
void lineFollow() { //function
	//Tweaking the values
	leftMotorSpeed = leftSensorValue-40;
	rightMotorSpeed = rightSensorValue-25;

	if (leftSensorValue < 20) { //emergency value
		leftMotorSpeed = -80;
		rightMotorSpeed = 80;
	}
	if (rightSensorValue < 20) {
		rightMotorSpeed = -80;
		leftMotorSpeed = 80;
	}

	setMotorSpeed(leftMotor, leftMotorSpeed); //Set leftMotor speed
	setMotorSpeed(rightMotor, rightMotorSpeed); //Set leftMotor speed
}

//Green, for right sensor
void rightSensorGreen() {
	if (getColorName(rightSensor) == colorGreen) {
		//Check if its really green
		setMotorSpeed(leftMotor, 10);
		setMotorSpeed(rightMotor, 10);
		sleep(50);
		if (getColorName(rightSensor) == colorGreen) {
			playSound(soundBlip);
			//turn
			moveMotorTarget(leftMotor, 360, 80);
			sleep(400);
		}
	}
}

//Green, for left sensor
void leftSensorGreen() {
	if (getColorName(leftSensor) == colorGreen) {
		//Check if its really green
		setMotorSpeed(leftMotor, 10);
		setMotorSpeed(rightMotor, 10);
		sleep(50);
		if (getColorName(leftSensor) == colorGreen) {
			playSound(soundBlip);
			//turn
			moveMotorTarget(rightMotor, 360, 80);
			sleep(400);
		}
		else {
		}
	}
}

void doubleGreen() {
	if (getColorName(leftSensor) == colorGreen || getColorName(leftSensor) == colorBlue || getColorName(leftSensor) == colorNone) {
		if (getColorName(rightSensor) == colorGreen || getColorName(rightSensor) == colorBlue || getColorName(leftSensor) == colorNone) {
			////Check if its really green
			//setMotorSpeed(leftMotor, 10);
			//setMotorSpeed(rightMotor, 10);
			//sleep(50);
			if (getColorName(leftSensor) == colorGreen || getColorName(leftSensor) == colorBlue || getColorName(leftSensor) == colorNone) {
				if (getColorName(leftSensor) == colorGreen || getColorName(leftSensor) == colorBlue || getColorName(leftSensor) == colorNone) {
					playSound(soundBeepBeep);
					setMotorSpeed(leftMotor, 30);
					setMotorSpeed(rightMotor, 50);
					sleep(1200);
					while (getUSDistance(S4) > 34) {
						setMotorSpeed(leftMotor, 10);
						setMotorSpeed(rightMotor, -10);
					}
					setMotorSpeed(leftMotor, 69.42);
					setMotorSpeed(rightMotor, -69.42);
					sleep(420+69);
					stopAllTasks();
				}
			}
		}
	}
	else {
		playSound(soundException);
		string tmp = getColorHue(leftSensor);
		displayBigTextLine(1, tmp);
		sleep(1000);
		stopAllTasks();
	}
}

task main()
{
	while (true) {
		leftSensorValue = getColorReflected(leftSensor); //Left sensor value
		rightSensorValue = getColorReflected(rightSensor); //Right sensor value

		//Display Values
		/*string leftValueString = leftSensorValue;
		string rightValueString = rightSensorValue;
		strcat(leftValueString, " ");
		strcat(leftValueString, rightValueString);
		string stringToDisplay = leftValueString;
		displayBigTextLine(1, stringToDisplay);*/

		//Green:
		if (leftSensorValue < 30) {
			leftSensorGreen();
		}
		if (rightSensorValue < 30) {
			rightSensorGreen();
		}
		if (leftSensorValue > 90) {
			if (rightSensorValue > 90) {
				setMotorSpeed(leftMotor, 10);
				setMotorSpeed(rightMotor, 10);
				sleep(500);
				doubleGreen();
			}
		}

		lineFollow();
	} //end of while loop
} //end of task main
