#pragma config(Sensor, S1,     leftSensor,     sensorEV3_Color)
#pragma config(Sensor, S2,     rightSensor,    sensorEV3_Color)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true) {
		float leftSensorValue = getColorReflected(leftSensor); //Left sensor value
		float rightSensorValue = getColorReflected(rightSensor); //Right sensor value

		//Tweaking the values
		leftSensorValue = leftSensorValue*2-150;
		rightSensorValue = rightSensorValue*2-150;

		setMotorSpeed(leftMotor, leftSensorValue); //Set leftMotor speed
		setMotorSpeed(rightMotor, rightSensorValue); //Set leftMotor speed
	}
}
