#pragma config(Sensor, S1,     leftSensor,     sensorEV3_Color)
#pragma config(Sensor, S2,     rightSensor,    sensorEV3_Color)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float leftSensorValue;
float rightSensorValue;

float leftMotorSpeed;
float rightMotorSpeed;

//Line following
void lineFollow() { //function
	//Tweaking the values
	leftMotorSpeed = leftSensorValue-30;
	rightMotorSpeed = rightSensorValue-30;

	if (leftSensorValue < 20) { //emergency value
		leftMotorSpeed = -80;
		rightMotorSpeed = 80;
	}
	if (rightSensorValue < 20) {
		rightMotorSpeed = -80;
		leftMotorSpeed = 80;
	}

	setMotorSpeed(leftMotor, leftMotorSpeed); //Set leftMotor speed
	setMotorSpeed(rightMotor, rightMotorSpeed); //Set leftMotor speed
}

//Green, for right sensor
void rightSensorGreen() {
	if (getColorName(rightSensor) == colorGreen) {
		//Check if its really green
		setMotorSpeed(leftMotor, 10);
		setMotorSpeed(rightMotor, 10);
		sleep(50);
		if (getColorName(rightSensor) == colorGreen) {
			playSound(soundBlip);
			//turn
			moveMotorTarget(leftMotor, 360, 80);
			sleep(400);
		}
	}
}

//Green, for left sensor
void leftSensorGreen() {
	if (getColorName(leftSensor) == colorGreen) {
		//Check if its really green
		setMotorSpeed(leftMotor, 10);
		setMotorSpeed(rightMotor, 10);
		sleep(50);
		if (getColorName(leftSensor) == colorGreen) {
			playSound(soundBlip);
			//turn
			moveMotorTarget(rightMotor, 360, 80);
			sleep(400);
		}
		else {
		}
	}
}

void doubleGreen() {
	if (getColorName(leftSensor) == colorGreen || getColorName(leftSensor) == colorBlue || getColorName(leftSensor) == colorNone) {
		if (getColorName(rightSensor) == colorGreen || getColorName(rightSensor) == colorBlue || getColorName(leftSensor) == colorNone) {
			////Check if its really green
			//setMotorSpeed(leftMotor, 10);
			//setMotorSpeed(rightMotor, 10);
			//sleep(50);
			if (getColorName(leftSensor) == colorGreen || getColorName(leftSensor) == colorBlue || getColorName(leftSensor) == colorNone) {
				if (getColorName(leftSensor) == colorGreen || getColorName(leftSensor) == colorBlue || getColorName(leftSensor) == colorNone) {
					playSound(soundBeepBeep);
					setMotorSpeed(leftMotor, 45);
					setMotorSpeed(rightMotor, 45);
					sleep(1200);
					int motorBSpinDistance;
					int motorCSpinDistance;
					resetMotorEncoder(leftMotor);
					resetMotorEncoder(rightMotor);
					while (getUSDistance(S4) > 30) {
						setMotorSpeed(leftMotor, 10);
						setMotorSpeed(rightMotor, -10);
					}
					motorBSpinDistance = getMotorEncoder(leftMotor);
					motorCSpinDistance = getMotorEncoder(rightMotor);
					int motorBBackupDistance;
					int motorCBackupDistance;
					resetMotorEncoder(leftMotor);
					resetMotorEncoder(rightMotor);
					setMotorSpeed(motorA, -33);
					setMotorSpeed(leftMotor, -30);
					setMotorSpeed(rightMotor, -30);
					sleep(300);
					while (getUSDistance(S4) < 20) {
						setMotorSpeed(leftMotor, -69.42);
						setMotorSpeed(rightMotor, -69.42);
					}
					motorBBackupDistance = getMotorEncoder(leftMotor);
					motorCBackupDistance = getMotorEncoder(rightMotor);
					moveMotorTarget(leftMotor, 350, 69);
					moveMotorTarget(rightMotor, 350, -69);
					sleep(1111);
					setMotorSpeed(leftMotor, -33);
					setMotorSpeed(rightMotor, -33);
					sleep(1334);
					setMotorSpeed(motorA, 120);
					sleep(433);
					setMotorSpeed(leftMotor, 20);
					setMotorSpeed(rightMotor, 20);
					setMotorSpeed(motorA, 120);
					sleep(666);
					setMotorSpeed(leftMotor, -15);
					setMotorSpeed(rightMotor, 15);
					setMotorSpeed(motorA, 120);
					sleep(500);

					//Return
					setMotorSpeed(motorA, -20);
					setMotorSpeed(leftMotor, 33);
					setMotorSpeed(rightMotor, 33);
					sleep(1334);
					moveMotorTarget(leftMotor, 350, 69);
					moveMotorTarget(rightMotor, 350, -69);
					sleep(1111);
					moveMotorTarget(leftMotor, motorBBackupDistance, 40);
					moveMotorTarget(rightMotor, motorCBackupDistance, 40);
					sleep(3000);
					moveMotorTarget(leftMotor, motorBSpinDistance, -70);
					moveMotorTarget(rightMotor, motorCSpinDistance, 70);
					sleep(3000);
				}
			}
		}
	}
	else {
		playSound(soundException);
		string tmp = getColorHue(leftSensor);
		displayBigTextLine(1, tmp);
		sleep(1000);
		stopAllTasks();
	}
}

task main()
{
	while (true) {
		leftSensorValue = getColorReflected(leftSensor); //Left sensor value
		rightSensorValue = getColorReflected(rightSensor); //Right sensor value

		//Display Values
		/*string leftValueString = leftSensorValue;
		string rightValueString = rightSensorValue;
		strcat(leftValueString, " ");
		strcat(leftValueString, rightValueString);
		string stringToDisplay = leftValueString;
		displayBigTextLine(1, stringToDisplay);*/

		//Green:
		if (leftSensorValue < 30) {
			leftSensorGreen();
		}
		if (rightSensorValue < 30) {
			rightSensorGreen();
		}
		if (leftSensorValue > 90) {
			if (rightSensorValue > 90) {
				setMotorSpeed(leftMotor, 10);
				setMotorSpeed(rightMotor, 10);
				sleep(500);
				doubleGreen();
			}
		}

		//Water tower thing idk what this is called
		if (getUSDistance(S4) < 5) {
			//Turn right
			moveMotorTarget(leftMotor, 180, 20);
			moveMotorTarget(rightMotor, 180, -20);
			sleep(3000);
			//Curve
			setMotorSpeed(leftMotor, 30);
			setMotorSpeed(rightMotor, 40);
			sleep(3000);
			//Turn right to meet the line
			moveMotorTarget(leftMotor, 180, 20);
			moveMotorTarget(rightMotor, 180, -20);
			sleep(3000);
		}

		lineFollow();
	} //end of while loop
} //end of task main
