#pragma config(Sensor, S1,     leftSensor,     sensorEV3_Color)
#pragma config(Sensor, S2,     rightSensor,    sensorEV3_Color)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Main line following
float leftSensorValue;
float rightSensorValue;
void lineFollow() { //function
	if (leftSensorValue < 20) { //emergency value
		leftSensorValue = -80;
		rightSensorValue = 80;
	}
	if (rightSensorValue < 20) {
		rightSensorValue = -80;
		leftSensorValue = 80;
	}

	setMotorSpeed(leftMotor, leftSensorValue); //Set leftMotor speed
	setMotorSpeed(rightMotor, rightSensorValue); //Set leftMotor speed

}

void rightSensorGreen() {
	if (rightSensorValue < 30) {
		if (getColorName(rightSensor) == colorGreen /*|| getColorName(leftSensor) == colorBlue*/) {
			playSound(soundBlip);
			//turn
			moveMotorTarget(motorB, 360, 80);
			sleep(250);
		}
		else {
			lineFollow();
		}
	}
	else {
		lineFollow();
	}
}

task main()
{
	while (true) {
		leftSensorValue = getColorReflected(leftSensor); //Left sensor value
		rightSensorValue = getColorReflected(rightSensor); //Right sensor value

		//Display Values
		/*string leftValueString = leftSensorValue;
		string rightValueString = rightSensorValue;
		strcat(leftValueString, " ");
		strcat(leftValueString, rightValueString);
		string stringToDisplay = leftValueString;
		displayBigTextLine(1, stringToDisplay);*/

		//Tweaking the values
		leftSensorValue = leftSensorValue/3;
		rightSensorValue = rightSensorValue/3;

		//Green
		if (leftSensorValue < 30) {
			if (getColorName(leftSensor) == colorGreen /*|| getColorName(leftSensor) == colorBlue*/) {
				playSound(soundBlip);
				//turn
				moveMotorTarget(motorC, 360, 80);
				sleep(250);
			}
			else {
				rightSensorGreen();
			}
		}
		else {
			rightSensorGreen();
		}
	} //end of while loop
} //end of task main
